'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../docs/index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements=new Map();
const writes=[];
const classes=()=>{const s=new Set();return {add:x=>s.add(x),remove:x=>s.delete(x),contains:x=>s.has(x),toggle:(x,on)=>on?s.add(x):s.delete(x)};};
const document={documentElement:{},querySelectorAll:()=>[],querySelector:s=>document.getElementById(s),addEventListener(){},getElementById(id){
  if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',classList:classes(),setAttribute(){}});
  return elements.get(id);
}};
let revoked=0;
const ctx=vm.createContext({document,setTimeout(){},clearTimeout(){},window:{scrollTo(){},addEventListener(){}},
 localStorage:{getItem(){return null;},setItem:(k,v)=>writes.push([k,v])},URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){revoked++;}}});
vm.runInContext(script,ctx);
const run=s=>vm.runInContext(s,ctx);
const initial=run('JSON.stringify(DATA)');
assert.equal(run("getDraft('1').rooms.length"),23);
assert.equal(run("getDraft('2').rooms.length"),27);
assert.throws(()=>run("buildImport(getDraft('1'),'1')"));
// Synthetic confirmed values are deliberately set, never inferred from missing input.
run(`for(const id of ['1','2']) {const d=getDraft(id);d.photo='blob:synthetic';d.date='2099-01-01';d.out='0';d.stay='0';d.ck='0';for(const r of d.rooms){r.in='○';for(const k of ['big','mid','small','infant'])r[k]='0';r.verified=true;}}`);
assert.equal(run("buildImport(getDraft('1'),'1').rooms.length"),23);
assert.equal(run("buildImport(getDraft('2'),'2').rooms.length"),27);
for(const invalid of ['', '-1','1.5','1e2','abc','9007199254740992']){
  ctx.bad=invalid;
  assert.equal(run('checkedNumber(bad)'),null);
}
run("getDraft('1').rooms[0].big=''");
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].big"),0,'confirmed blank people are zero');
run("getDraft('1').rooms[0].verified=false");
assert.throws(()=>run("buildImport(getDraft('1'),'1')"),'room must be checked even when numeric blanks count as zero');
run("getDraft('1').rooms[0].verified=true");
run("getDraft('1').rooms[0].big='2';getDraft('1').rooms[0].mid='1';getDraft('1').rooms[0].small='1';getDraft('1').rooms[0].infant='1'");
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].mouth"),4);
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].slippers"),5);
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].notes[0].ja"),"子供セット×3");
run("getDraft('1').rooms[0].overrides={slippers:'9',samue:'6'}");
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].slippers"),9);
assert.equal(run("buildImport(getDraft('1'),'1').rooms[0].towel"),6);
run("getDraft('1').rooms[0].overrides={}");
run("getDraft('1').date='2099-02-30'");
assert.throws(()=>run("buildImport(getDraft('1'),'1')"));
run("getDraft('1').date='2099-01-01';getDraft('1').rooms[0].noteJa='<img src=https://example.invalid/secret onerror=alert(1)>'");
assert.throws(()=>run("buildImport(getDraft('1'),'1')"),'notes require both languages');
run("getDraft('1').rooms[0].noteNe='परीक्षण टिप्पणी';openImport();reviewImport()");
assert.equal(run('JSON.stringify(DATA)'),initial,'review cannot change the cards');
const review=document.getElementById('import-content').innerHTML;
assert(review.includes('id="review-room-1101"'));
assert(!review.includes('id="room-1101"'),'preview IDs do not shadow floor scroll targets');
assert(review.includes('&lt;img src=https://example.invalid/secret onerror=alert(1)&gt;'));
assert(!review.includes('<img src=https://example.invalid/secret'),'custom notes escaped');
run('applyImport()');
assert.equal(run('JSON.stringify(DATA)'),initial,'human confirmation required');
document.getElementById('import-agree').checked=true;
run('applyImport()');
assert.equal(run("DATA['1'].source"),'local');
assert.equal(run("DATA['2'].source"),undefined,'other building still has demo data');
run("setLanguage('ne')");
assert(document.getElementById('rooms').innerHTML.includes('परीक्षण टिप्पणी'));
assert(!document.getElementById('rooms').innerHTML.includes('&lt;img'));
run("importBuilding='2';reviewImport();applyImport()");
assert.equal(run("DATA['2'].source"),'local');
assert.equal(run("DATA['1'].rooms.length+DATA['2'].rooms.length"),50);
run("openImport();selectImportBuilding('1')");
assert.equal(run("getDraft('1').rooms[0].big"),'2','draft survives building switch');
run("choosePhoto({target:{files:[{type:'text/plain',size:1}]}})");
assert.equal(run("getDraft('1').photo"),'blob:synthetic');
run("choosePhoto({target:{files:[{type:'image/png',size:21*1024*1024}]}})");
assert(document.getElementById('import-error').textContent.length>0);
run("choosePhoto({target:{files:[{type:'image/png',size:100}]}})");
assert.equal(revoked,1,'old local image URL revoked');
assert.equal(run("getDraft('1').rooms.every(r=>!r.verified)"),true,'new photo requires all rooms to be rechecked');
assert.deepEqual(writes,[['cleaning-web-language','ne']],'operational data never persisted');
assert(!/\b(?:fetch|XMLHttpRequest|WebSocket|sendBeacon|indexedDB)\b/.test(script),'no network or operational persistence APIs');
assert(html.includes("connect-src 'none'; form-action 'none'"));
assert(!/<script[^>]+src=|<link[^>]+href=/i.test(html),'no external assets');
const fresh=vm.createContext({...ctx});vm.runInContext(script,fresh);
assert.equal(vm.runInContext('hasLocalData()',fresh),false,'reload discards imported data');
console.log('OK: per-building local photo drafts, missing-value rejection, human review, bilingual notes, escaping and no data persistence');
